In [8]:
import pandas as pd 
import seaborn as sns

df = sns.load_dataset('tips')
df.head()

   total_bill   tip     sex smoker  day    time  size
0       16.99  1.01  Female     No  Sun  Dinner     2
1       10.34  1.66    Male     No  Sun  Dinner     3
2       21.01  3.50    Male     No  Sun  Dinner     3
3       23.68  3.31    Male     No  Sun  Dinner     2
4       24.59  3.61  Female     No  Sun  Dinner     4

In [9]:
from sklearn.preprocessing import LabelEncoder
encoder_time = LabelEncoder()

encoded_data = encoder_time.fit_transform(df['time'])
print('classes:', encoder_time.classes_)
encoded_data

classes: ['Dinner' 'Lunch']

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0])

In [10]:
for category, number in zip(encoder_time.classes_, range(len(encoder_time.classes_))):
    print(category, '----------', number)

Dinner ---------- 0
Lunch ---------- 1

In [11]:
encoder_day = LabelEncoder()

encoded_day_data = encoder_day.fit_transform(df['day'])
print('classes:', encoder_day.classes_)

classes: ['Fri' 'Sat' 'Sun' 'Thur']

In [12]:
for category, number in zip(encoder_day.classes_, range(len(encoder_day.classes_))):
    print(category, '----------', number)

Fri ---------- 0
Sat ---------- 1
Sun ---------- 2
Thur ---------- 3

In [13]:
encoder_day.inverse_transform([0, 1, 2, 3])

array(['Fri', 'Sat', 'Sun', 'Thur'], dtype=object)

In [14]:
from sklearn.preprocessing import OneHotEncoder

ohe = OneHotEncoder(sparse_output=False, drop='first')

ohe_encoder = ohe.fit_transform(df[['sex', 'smoker']])
ohe_encoder

array([[0., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [0., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [0., 0.],
       [1., 0.],
       [1., 0.],
       [0., 0.],
       [1., 0.],
       [0., 0.],
       [1., 0.],
       [0., 0.],
       [1., 0.],
       [1., 0.],
       [0., 0.],
       [0., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [0., 0.],
       [1., 0.],
       [1., 0.],
       [0., 0.],
       [0., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [0., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [0., 0.],
       [0., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 1.],
       [0., 0.],
       [1., 1.],
       [1., 0.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 0.],
       [1., 0.],
       [0., 0.],
       [0., 1.],
       [1., 0.],
       [1., 1.],
       [1., 0.],
       [0., 0.],
       [0., 1.],
       [0., 1.],
       [0., 0.],
       [1., 0.],
       [1., 1.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 1.],
       [1., 0.],
       [0., 0.],
       [1., 1.],
       [1., 0.],
       [0., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 1.],
       [1., 0.],
       [0., 1.],
       [0., 1.],
       [0., 0.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 0.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 0.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 0.],
       [0., 1.],
       [1., 0.],
       [0., 0.],
       [1., 0.],
       [1., 0.],
       [0., 0.],
       [0., 0.],
       [1., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [1., 0.],
       [0., 0.],
       [1., 0.],
       [1., 0.],
       [0., 0.],
       [0., 0.],
       [1., 0.],
       [0., 0.],
       [0., 0.],
       [1., 0.],
       [1., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [1., 1.],
       [0., 0.],
       [0., 0.],
       [1., 0.],
       [1., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [0., 0.],
       [1., 0.],
       [0., 0.],
       [0., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [0., 0.],
       [1., 0.],
       [0., 1.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [0., 1.],
       [0., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [0., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 0.],
       [0., 1.],
       [1., 1.],
       [0., 1.],
       [1., 1.],
       [1., 1.],
       [0., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 0.],
       [1., 1.],
       [0., 1.],
       [0., 1.],
       [1., 1.],
       [1., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [1., 1.],
       [0., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [0., 1.],
       [1., 1.],
       [1., 1.],
       [1., 0.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [0., 1.],
       [1., 1.],
       [0., 1.],
       [1., 1.],
       [0., 0.],
       [1., 1.],
       [0., 1.],
       [0., 1.],
       [1., 0.],
       [1., 0.],
       [0., 1.],
       [1., 1.],
       [1., 1.],
       [1., 0.],
       [1., 0.],
       [1., 1.],
       [1., 0.],
       [1., 1.],
       [1., 1.],
       [0., 0.],
       [1., 0.],
       [0., 1.],
       [1., 1.],
       [1., 0.],
       [0., 0.]])

In [15]:
df1 = pd.DataFrame(ohe_encoder, columns=ohe.get_feature_names_out())
df1

     sex_Male  smoker_Yes
0         0.0         0.0
1         1.0         0.0
2         1.0         0.0
3         1.0         0.0
4         0.0         0.0
..        ...         ...
239       1.0         0.0
240       0.0         1.0
241       1.0         1.0
242       1.0         0.0
243       0.0         0.0

[244 rows x 2 columns]

In [16]:
pd.concat([df, df1], axis=1)

     total_bill   tip     sex smoker   day    time  size  sex_Male  smoker_Yes
0         16.99  1.01  Female     No   Sun  Dinner     2       0.0         0.0
1         10.34  1.66    Male     No   Sun  Dinner     3       1.0         0.0
2         21.01  3.50    Male     No   Sun  Dinner     3       1.0         0.0
3         23.68  3.31    Male     No   Sun  Dinner     2       1.0         0.0
4         24.59  3.61  Female     No   Sun  Dinner     4       0.0         0.0
..          ...   ...     ...    ...   ...     ...   ...       ...         ...
239       29.03  5.92    Male     No   Sat  Dinner     3       1.0         0.0
240       27.18  2.00  Female    Yes   Sat  Dinner     2       0.0         1.0
241       22.67  2.00    Male    Yes   Sat  Dinner     2       1.0         1.0
242       17.82  1.75    Male     No   Sat  Dinner     2       1.0         0.0
243       18.78  3.00  Female     No  Thur  Dinner     2       0.0         0.0

[244 rows x 9 columns]

In [17]:
from sklearn.preprocessing import FunctionTransformer
import numpy as np

log = FunctionTransformer(np.log10)
print(log.fit_transform(df['tip']))

log2 = FunctionTransformer(np.log2)
print(log2.fit_transform(df['tip']))

0      0.004321
1      0.220108
2      0.544068
3      0.519828
4      0.557507
         ...
239    0.772322
240    0.301030
241    0.301030
242    0.243038
243    0.477121
Name: tip, Length: 244, dtype: float64
0      0.014355
1      0.731183
2      1.807355
3      1.726831
4      1.851999
         ...
239    2.565597
240    1.000000
241    1.000000
242    0.807355
243    1.584963
Name: tip, Length: 244, dtype: float64

In [18]:
from sklearn.preprocessing import PowerTransformer
import numpy as np

# A right-skewed feature
x = np.array([[-1], [0], [3], [5], [10], [50]])

# Create the transformer
pt = PowerTransformer(method='yeo-johnson')

# Fit and Transform
X_transformed = pt.fit_transform(x)
print('original:')
print(x.ravel())
print('\nTransformed:')
print(np.round(X_transformed.ravel(), 3))
print('\nLearned lambda:')
print(pt.lambdas_)

original:
[-1  0  3  5 10 50]

Transformed:
[-1.54  -0.801 -0.045  0.195  0.571  1.619]

Learned lambda:
[0.09126797]

In [19]:
# Positive values for Box-Cox
x_pos = np.array([[1], [2], [3], [5], [10], [50]])

# Create the transformer
pt_box = PowerTransformer(method='box-cox')

# Fit and Transform
Y_transformed = pt_box.fit_transform(x_pos)
print('original:')
print(x_pos.ravel())
print('\nTransformed:')
print(np.round(Y_transformed.ravel(), 3))
print('\nLearned lambda:')
print(pt_box.lambdas_)

original:
[ 1  2  3  5 10 50]

Transformed:
[-1.519 -0.696 -0.282  0.178  0.708  1.612]

Learned lambda:
[-0.27346888]

In [20]:
import numpy as np
import pandas as pd

data = {
    'Name': ['Aarav', 'Priya', 'Rohit', 'Sneha', 'Arjun', 'Neha', 'Karan', 'Pooja', 'Vikram', 'Ananya'],
    # Categorical Columns
    'Gender': ['Male', 'Female', np.nan, 'Female', 'Male', 'Female', 'Male', np.nan, 'Male', 'Female'],
    'Department': ['IT', 'HR', 'Finance', np.nan, 'IT', 'HR', np.nan, 'Marketing', 'Finance', 'IT'],
    'City': ['Mumbai', 'Delhi', 'Bengaluru', 'Mumbai', np.nan, 'Pune', 'Delhi', 'Bengaluru', np.nan, 'Pune'],
    # Numerical Columns
    'Age': [25, 28, np.nan, 22, 30, np.nan, 27, 24, 35, 29],
    'Salary': [50000, 62000, 58000, np.nan, 75000, 48000, 67000, np.nan, 85000, 72000],
    'Experience_Years': [2, 4, 3, 1, np.nan, 3, np.nan, 2, 8, 5]
}

df_missing = pd.DataFrame(data)
print(df_missing.isnull().sum())
df_missing

Name                0
Gender              2
Department          2
City                2
Age                 2
Salary              2
Experience_Years    2
dtype: int64

     Name  Gender Department       City   Age   Salary  Experience_Years
0   Aarav    Male         IT     Mumbai  25.0  50000.0               2.0
1   Priya  Female         HR      Delhi  28.0  62000.0               4.0
2   Rohit     NaN    Finance  Bengaluru   NaN  58000.0               3.0
3   Sneha  Female        NaN     Mumbai  22.0      NaN               1.0
4   Arjun    Male         IT        NaN  30.0  75000.0               NaN
5    Neha  Female         HR       Pune   NaN  48000.0               3.0
6   Karan    Male        NaN      Delhi  27.0  67000.0               NaN
7   Pooja     NaN  Marketing  Bengaluru  24.0      NaN               2.0
8  Vikram    Male    Finance        NaN  35.0  85000.0               8.0
9  Ananya  Female         IT       Pune  29.0  72000.0               5.0

In [21]:
from sklearn.impute import SimpleImputer

imputer = SimpleImputer(strategy='mean')
df_missing['new_salary'] = imputer.fit_transform(df_missing[['Salary']]).flatten()
df_missing

,Name,Gender,Department,City,Age,Salary,Experience_Years,new_salary
0,Aarav,Male,IT,Mumbai,25.0,50000.0,2.0,50000.0
1,Priya,Female,HR,Delhi,28.0,62000.0,4.0,62000.0
2,Rohit,NaN,Finance,Bengaluru,NaN,58000.0,3.0,58000.0
3,Sneha,Female,NaN,Mumbai,22.0,NaN,1.0,64625.0
4,Arjun,Male,IT,NaN,30.0,75000.0,NaN,75000.0
5,Neha,Female,HR,Pune,NaN,48000.0,3.0,48000.0
6,Karan,Male,NaN,Delhi,27.0,67000.0,NaN,67000.0
7,Pooja,NaN,Marketing,Bengaluru,24.0,NaN,2.0,64625.0
8,Vikram,Male,Finance,NaN,35.0,85000.0,8.0,85000.0
9,Ananya,Female,IT,Pune,29.0,72000.0,5.0,72000.0

In [22]:
imputer_med = SimpleImputer(strategy='median')
df_missing['new_Experience_Years'] = imputer_med.fit_transform(df_missing[['Experience_Years']]).flatten()
df_missing

,Name,Gender,Department,City,Age,Salary,Experience_Years,new_salary,new_Experience_Years
0,Aarav,Male,IT,Mumbai,25.0,50000.0,2.0,50000.0,2.0
1,Priya,Female,HR,Delhi,28.0,62000.0,4.0,62000.0,4.0
2,Rohit,NaN,Finance,Bengaluru,NaN,58000.0,3.0,58000.0,3.0
3,Sneha,Female,NaN,Mumbai,22.0,NaN,1.0,64625.0,1.0
4,Arjun,Male,IT,NaN,30.0,75000.0,NaN,75000.0,3.0
5,Neha,Female,HR,Pune,NaN,48000.0,3.0,48000.0,3.0
6,Karan,Male,NaN,Delhi,27.0,67000.0,NaN,67000.0,3.0
7,Pooja,NaN,Marketing,Bengaluru,24.0,NaN,2.0,64625.0,2.0
8,Vikram,Male,Finance,NaN,35.0,85000.0,8.0,85000.0,8.0
9,Ananya,Female,IT,Pune,29.0,72000.0,5.0,72000.0,5.0

In [23]:
imputer_mode = SimpleImputer(strategy='most_frequent')
df_missing['new_City'] = imputer_mode.fit_transform(df_missing[['City']]).flatten()
df_missing

,Name,Gender,Department,City,Age,Salary,Experience_Years,new_salary,new_Experience_Years,new_City
0,Aarav,Male,IT,Mumbai,25.0,50000.0,2.0,50000.0,2.0,Mumbai
1,Priya,Female,HR,Delhi,28.0,62000.0,4.0,62000.0,4.0,Delhi
2,Rohit,NaN,Finance,Bengaluru,NaN,58000.0,3.0,58000.0,3.0,Bengaluru
3,Sneha,Female,NaN,Mumbai,22.0,NaN,1.0,64625.0,1.0,Mumbai
4,Arjun,Male,IT,NaN,30.0,75000.0,NaN,75000.0,3.0,Bengaluru
5,Neha,Female,HR,Pune,NaN,48000.0,3.0,48000.0,3.0,Pune
6,Karan,Male,NaN,Delhi,27.0,67000.0,NaN,67000.0,3.0,Delhi
7,Pooja,NaN,Marketing,Bengaluru,24.0,NaN,2.0,64625.0,2.0,Bengaluru
8,Vikram,Male,Finance,NaN,35.0,85000.0,8.0,85000.0,8.0,Bengaluru
9,Ananya,Female,IT,Pune,29.0,72000.0,5.0,72000.0,5.0,Pune